export default {
  grid: {
    container: '130rem',
    gutter: '3.2rem',
  },
  border: {
    radius: {
      xlg: '3.125rem',
      medium: '1.125rem',
      xsmall: '0.8rem',
      xxsmall: '0.4rem',
    },
  },
  font: {
    light: 300,
    normal: 400,
    bold: 600,
    medium: 500,
    sizes: {
      xsmall: '1.2rem',
      small: '1.4rem',
      medium: '1.6rem',
      large: '1.8rem',
      xlarge: '2.0rem',
      xxlarge: '2.8rem',
    },
  },
  colors: {
    primary: '#486284',
    secondary: '#DEE5ED',
    tertiary: '#9CB0C9',
    quaternary: '#7C93B0',
    mainBg: '#FFF',
    white: '#FAFAFA',
    black: '#030517',
    lightGray: '#EAEAEA',
    gray: '#8F8F8F',
  },
  spacings: {
    xxsmall: '0.8rem',
    xsmall: '1.6rem',
    small: '2.4rem',
    medium: '3.2rem',
    large: '4.0rem',
    xlarge: '4.8rem',
    xxlarge: '5.6rem',
  },
  layers: {
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
  breakpoints: {
    xs: '320px',
    sm: '450px',
    md: '768px',
    lg: '1170px',
    xl: '1440px',
  },
};
